#ifndef WA_MACRO_H
#define WA_MACRO_H

#define WA_WASAPI_OK					0x0000
#define WA_WASAPI_ENDOFFILE				0x0001
#define WA_WASAPI_INPUTERROR			0x0002
#define WA_WASAPI_MALLOCERROR			0x0003
#define WA_WASAPI_NOBYTESTOWRITE		0x0004
#define WA_WASAPI_BUFFERUNDERRUN		0x0005
#define WA_WASAPI_DEVICEWRITEERROR		0x0006

// Use in WaitSingleObject or Multiple Object Timeout
#define WA_WASAPI_MAX_WAIT_TIME_MS		1000

#endif
